"""initial migration

Revision ID: b07a460a1ba0
Revises: 
Create Date: 2026-08-18 22:09:59.850175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b07a460a1ba0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'is_verified',
            sa.Boolean(),
            server_default=sa.text('false'),
            nullable=False
        )
    )
    op.add_column(
        "users",
        sa.Column(
            "password_verification",
            sa.String(),
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_verification')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
